#!/bin/bash

MNT_LOCAL=/root
MNT_PMEM=/mnt/pmem
MNT_IOPMEM=/mnt/iopmem
MNT_NVME=/mnt/nvme

./test -v -l 0 --mmap ${MNT_LOCAL}/tst --odirect $MNT_NVME/tst
sleep 1
./test -vz -l 0 --mmap ${MNT_PMEM}/tst --odirect $MNT_NVME/tst
sleep 1
./test -vz -l 0 --mmap ${MNT_IOPMEM}/tst --odirect $MNT_NVME/tst
