#!/bin/bash

MNT_LOCAL=/root
MNT_PMEM=/mnt/pmem
MNT_IOPMEM=/mnt/iopmem
MNT_NVME=/mnt/nvme

./test -v --mmap ${MNT_LOCAL}/tst --odirect $MNT_NVME/tst
./test -vz --mmap ${MNT_PMEM}/tst --odirect $MNT_NVME/tst
./test -vz --mmap ${MNT_IOPMEM}/tst --odirect $MNT_NVME/tst
